testing:
  sampling:
    measurements_count: 20 #NULL
    total_duration_seconds: 3 #NULL
    sampling_frequency_hz: NULL

ammeters:
 greenlee:
   port: 5001
   class: "GreenleeAmmeter"
   command: "MEASURE_GREENLEE -get_measurement"
 entes:
   port: 5002
   class: "EntesAmmeter"
   command: "MEASURE_ENTES -get_data"
 circutor:
   port: 5003
   class: "CircutorAmmeter"
   command: "MEASURE_CIRCUTOR -get_measurement -current"
 circutor_extra:
   port: 5004
   class: "CircutorAmmeter"
   command: "MEASURE_CIRCUTOR -get_measurement -current"
analysis:
  statistical_metrics:
    mean: true
    median: true
    std: true
    min: true
    max: true
  visualization:
    enabled: true
    plot_types:
      - histogram
result_management: 
  save_results: true
  repository_path: "results/"
  